banking:
  enabled: false
  min_credits_to_bank: 25000
connection:
  game_letter: B
  host: localhost
  port: 2002
session:
  max_turns_per_session: 0
  target_credits: 500000
trading:
  policy: dynamic
  opportunistic:
    explore_chance: 0.3
    max_wander_without_trade: 5
  strategy: profitable_pairs
upgrades:
  enabled: false
